sudo: false
language: node_js
node:
- stable
install:
- npm install
before_script:
- npm ci
script:
- npm run build
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.bash
env:
  secure: ODxT6E/dlsurUnExFFXvuhw4I2u3S7LCUWRhYxBlbJ25YyUPE2a3zPWWJeif7FWmO31stF2IK+w9rg8Mx0eX8TGOF3Rv+S4TzkaS4IY2rc9a0lXLq/JmX9MbTWps7ey86ybrQctr7S+J1b5yIMdiQWjM7Ar0GhmVdipFpKnVVakRHbHO20F+zqx/Vsb/E8S+vaciPH8RZJzb0Z5N1SK/G0KjE8gHt90dz1xlv1EJE+vPYWXUg6u60AMz60wp8moWxjevfWRz2oH52M+gHbxnn93gJtXPfK7/Jbm02IPte97tzTgJMdVO81Wiade3QZYp1C0tevSdCkcYDu25vZ6M4aqJ3/wi3rjvN22UfmdLy930AzhaIAOlE06AIFMZrDNvh6XOWjQNvI75fBGQSYQcMXz2dDKbBzEJKgMu+cl29KGY9i8Xlz4lmBBF5S3RHbArK/4+v4pwWLjVl9HnP9KFfGvNWTzbR3r2ttXw2EGboNPK9cWy4TtSYa9McTNa5dUnBRdy1EORGFhMrarGOOm+J89Lc6SEwEQgseYIIbm66lgH7F+6p0ZTI8590NW9RtFOAKueA+VIU5coftRiA8AgmkgCLSAi7NzGIctD3ED/D6JhHiNzXYnSwQWL3YRdvf3ZvNBKX/6rwp6QZvjByzjj+IOLK6F2z37+KiwAoN6oqgg=
